version: "3.9"

services:
  app:
    build:
      context: . # build docker in current directory
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app # mapping directory in our systems with the docker container this is to update
                   # the changes we make in our code to be reflected in the container in real time
    command: >
      sh -c "python manage.py wait_for_db && 
             python manage.py  migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme


volumes:
  dev-db-data:
